check undefined count

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,3 +30,7 @@ jobs:
           ldd lib/libfam.so  | grep "statically linked" || { echo "not statically linked!"; exit 1; }
           UNDEFINED_COUNT=$(nm lib/libfam.so | grep " U " | grep -v "U environ" | wc -l)
           echo $UNDEFINED_COUNT
+          if [ "$UNDEFINED_COUNT" -ne 0 ]; then
+            echo "Error: Found $UNDEFINED_COUNT undefined symbols other than environ"
+            exit 1
+          fi
